Almost there
Why the objectslist is showing as std::vector<Object> instead of
std::vector<Object *>???????

Error C2664 'void KX_Scene::ConvertBlenderObjectsList(std::vector<Object
*,std::allocator<Object *>>,bool)': argument 1 can not be converted from
'std::vector<Object,std::allocator<Object>>' to 'std::vector<Object
*,std::allocator<Object *>>'
ge_ketsji
E:\Development\blender-upbge-eevee\source\gameengine\Ketsji\KX_Scene.cpp
2988